// 成就数据
import { Achievement } from '@/types/achievement';

export const achievementsData: Record<string, Achievement> = {
  a1: {
    id: 'a1',
    name: '初入修行',
    description: '修为达到 100 点，踏出修行第一步。',
    type: 'xiuwei',
    target: '100',
    amount: 100,
    reward: { xiuwei: 50 },
  },
  a2: {
    id: 'a2',
    name: '初出茅庐',
    description: '击败过至少一种敌人。',
    type: 'combat_win',
    target: '1',
    amount: 1,
    reward: { items: ['liao_shang_dan'] },
  },
  a3: {
    id: 'a3',
    name: '身经百战',
    description: '击败过五种不同的敌人。',
    type: 'combat_win',
    target: '5',
    amount: 5,
    reward: { items: ['duan_ti_dan'] },
  },
  a4: {
    id: 'a4',
    name: '斩妖除魔',
    description: '斩杀断魂崖霸主黑风妖。',
    type: 'kill_enemy',
    target: 'hei_feng_yao',
    reward: { lingShi: 200 },
  },
  a5: {
    id: 'a5',
    name: '山妖克星',
    description: '斩杀青木岭的山妖狼。',
    type: 'kill_enemy',
    target: 'shan_yao_lang',
    reward: { items: ['yao_shou_ge'] },
  },
  a6: {
    id: 'a6',
    name: '第一次突破',
    description: '突破至开脉境界。',
    type: 'breakthrough',
    target: 'kai_mai',
    reward: { lingShi: 100 },
  },
  a7: {
    id: 'a7',
    name: '筑基有成',
    description: '突破至筑基境界，筑下道基。',
    type: 'breakthrough',
    target: 'zhu_ji',
    reward: { items: ['ju_qi_dan', 'ju_qi_dan', 'ju_qi_dan'] },
  },
  a8: {
    id: 'a8',
    name: '落星坡行者',
    description: '到访落星坡的全部地点。',
    type: 'visit_all',
    target: 'all',
    reward: { lingShi: 200 },
  },
  a9: {
    id: 'a9',
    name: '富甲一方',
    description: '身上灵石达到 500 枚。',
    type: 'lingShi',
    target: '500',
    amount: 500,
    reward: { items: ['ju_ling_dan'] },
  },
  a10: {
    id: 'a10',
    name: '收集者',
    description: '背包中拥有 10 种不同的物品。',
    type: 'inventory_kind',
    target: '10',
    amount: 10,
    reward: { items: ['yu_pei'] },
  },
  a11: {
    id: 'a11',
    name: '修为小成',
    description: '修为达到 3000 点。',
    type: 'xiuwei',
    target: '3000',
    amount: 3000,
    reward: { items: ['yin_qi_jue'] },
  },
  a12: {
    id: 'a12',
    name: '除魔卫道',
    description: '完成主线任务「斩妖除魔」。',
    type: 'quest_complete',
    target: 'q5',
    reward: { lingShi: 300 },
  },
};
