// 物品数据（丹药 / 材料 / 法宝 / 功法 / 杂物）
import { Item } from '@/types/item';

export const itemsData: Record<string, Item> = {
  /* ===== 丹药 ===== */
  liao_shang_dan: {
    id: 'liao_shang_dan',
    name: '疗伤丹',
    type: 'dan',
    rarity: 'ling',
    description: '以灵草炼制的一品丹药，服下可温养气血，恢复伤势。',
    effect: { type: 'restore_hp', value: 50, desc: '恢复气血 50 点' },
    price: 30,
    stackable: true,
  },
  ju_qi_dan: {
    id: 'ju_qi_dan',
    name: '聚气丹',
    type: 'dan',
    rarity: 'ling',
    description: '蕴含精纯灵气，服下可助炼化灵气，增进修为。',
    effect: { type: 'gain_xiuwei', value: 60, desc: '修为 +60' },
    price: 40,
    stackable: true,
  },
  ning_shen_dan: {
    id: 'ning_shen_dan',
    name: '凝神丹',
    type: 'dan',
    rarity: 'ling',
    description: '清心凝神，可提升道心明澈，稳固心境。',
    effect: { type: 'gain_daoxin', value: 5, desc: '道心 +5' },
    price: 50,
    stackable: true,
  },
  ju_ling_dan: {
    id: 'ju_ling_dan',
    name: '聚灵丹',
    type: 'dan',
    rarity: 'xuan',
    description: '引天地灵气入体，充盈灵蕴，强化丹田。',
    effect: { type: 'gain_lingyun', value: 6, desc: '灵蕴 +6' },
    price: 70,
    stackable: true,
  },
  duan_ti_dan: {
    id: 'duan_ti_dan',
    name: '锻体丹',
    type: 'dan',
    rarity: 'xuan',
    description: '淬炼肉身，增强体魄，使皮肉如铁。',
    effect: { type: 'gain_tipo', value: 3, desc: '体魄 +3' },
    price: 80,
    stackable: true,
  },
  hui_ling_dan: {
    id: 'hui_ling_dan',
    name: '回灵丹',
    type: 'dan',
    rarity: 'ling',
    description: '比疗伤丹更胜一筹的恢复丹药，可迅速温养气血。',
    effect: { type: 'restore_hp', value: 100, desc: '恢复气血 100 点' },
    price: 60,
    stackable: true,
  },
  zhu_ji_dan: {
    id: 'zhu_ji_dan',
    name: '筑基丹',
    type: 'dan',
    rarity: 'xuan',
    description: '汇聚灵材精粹的珍品丹药，服下可大幅增进修为，助人冲击筑基。',
    effect: { type: 'gain_xiuwei', value: 300, desc: '修为 +300' },
    price: 200,
    stackable: true,
  },
  jin_dan_po: {
    id: 'jin_dan_po',
    name: '金丹破障丹',
    type: 'dan',
    rarity: 'xuan',
    description: '以星魄碎片为主药炼制的珍品丹药，可助修士冲破金丹瓶颈。',
    effect: { type: 'gain_xiuwei', value: 800, desc: '修为 +800' },
    price: 350,
    stackable: true,
  },

  /* ===== 材料 ===== */
  ling_cao: {
    id: 'ling_cao',
    name: '灵草',
    type: 'cailiao',
    rarity: 'fan',
    description: '蕴含淡淡灵气的野草，炼丹炼器的常用材料。',
    price: 12,
    stackable: true,
  },
  qing_mu_ling_cai: {
    id: 'qing_mu_ling_cai',
    name: '青木灵枝',
    type: 'cailiao',
    rarity: 'ling',
    description: '青木岭特产的灵木枝干，质地坚韧，可炼器。',
    price: 25,
    stackable: true,
  },
  yao_shou_ge: {
    id: 'yao_shou_ge',
    name: '妖兽皮革',
    type: 'cailiao',
    rarity: 'ling',
    description: '从妖兽身上剥下的皮革，缝制护甲的上好材料。',
    price: 30,
    stackable: true,
  },
  yao_he: {
    id: 'yao_he',
    name: '妖兽内丹',
    type: 'cailiao',
    rarity: 'xuan',
    description: '强大妖兽体内凝结的内丹，蕴含庞大灵力，极为珍贵。',
    price: 80,
    stackable: true,
  },
  bai_cao_zhi: {
    id: 'bai_cao_zhi',
    name: '百年灵药',
    type: 'cailiao',
    rarity: 'xuan',
    description: '汲取百年灵气的药草，通体流转灵光，是炼制筑基丹的主药。',
    price: 60,
    stackable: true,
  },
  heiyu: {
    id: 'heiyu',
    name: '黑玉',
    type: 'cailiao',
    rarity: 'ling',
    description: '一种泛着幽光的黑色玉石，坊市间时有流通，来路不明。',
    price: 35,
    stackable: true,
  },
  xing_po_sui_pian: {
    id: 'xing_po_sui_pian',
    name: '星魄碎片',
    type: 'cailiao',
    rarity: 'xuan',
    description: '黑风妖体内的古星碎片，流转着幽蓝星光。它似乎在呼应着什么——那是古星陨落时散落此界的残力。',
    price: 100,
    stackable: false,
  },

  /* ===== 法宝（装备） ===== */
  tie_jian: {
    id: 'tie_jian',
    name: '玄铁剑',
    type: 'fabao',
    rarity: 'ling',
    description: '以玄铁铸成的长剑，锋锐无匹，是散修常用的兵刃。',
    equipSlot: 'weapon',
    atkBonus: 8,
    price: 150,
    stackable: false,
  },
  bu_yi: {
    id: 'bu_yi',
    name: '粗布道袍',
    type: 'fabao',
    rarity: 'fan',
    description: '寻常道袍，聊胜于无。',
    equipSlot: 'armor',
    defBonus: 4,
    price: 60,
    stackable: false,
  },
  hu_jia: {
    id: 'hu_jia',
    name: '兽皮护甲',
    type: 'fabao',
    rarity: 'ling',
    description: '以妖兽皮革鞣制而成的护甲，轻便坚韧。',
    equipSlot: 'armor',
    defBonus: 8,
    price: 120,
    stackable: false,
  },
  yu_pei: {
    id: 'yu_pei',
    name: '温玉护符',
    type: 'fabao',
    rarity: 'ling',
    description: '随身温养的一块灵玉，可护体辟邪，亦能助攻击势。',
    equipSlot: 'accessory',
    atkBonus: 2,
    defBonus: 3,
    price: 100,
    stackable: false,
  },
  qing_yang_jian: {
    id: 'qing_yang_jian',
    name: '青阳剑',
    type: 'fabao',
    rarity: 'xuan',
    description: '青阳宗制式佩剑，剑身流转淡青灵光，锋锐远胜凡铁。',
    equipSlot: 'weapon',
    atkBonus: 14,
    price: 300,
    stackable: false,
  },

  /* ===== 功法 ===== */
  yin_qi_jue: {
    id: 'yin_qi_jue',
    name: '引气诀',
    type: 'gongfa',
    rarity: 'fan',
    description: '最基础的吐纳功法，修习可大幅提升炼化灵气之效。',
    effect: { type: 'gain_xiuwei', value: 200, desc: '修为 +200' },
    price: 90,
    stackable: false,
  },
  bai_cao_ji: {
    id: 'bai_cao_ji',
    name: '百草集',
    type: 'gongfa',
    rarity: 'ling',
    description: '药王谷流出的炼丹手札，虽非功法，参悟间却似有灵气灌顶。',
    effect: { type: 'gain_xiuwei', value: 500, desc: '修为 +500' },
    price: 250,
    stackable: false,
  },

  /* ===== 杂物 ===== */
  po_miao_fu: {
    id: 'po_miao_fu',
    name: '山神符箓',
    type: 'za_wu',
    rarity: 'fan',
    description: '从破庙神像底座下拾得的残破符箓，边缘焦黑，隐约有字迹。',
    price: 5,
    stackable: true,
  },
  yu_jian_sui_pian: {
    id: 'yu_jian_sui_pian',
    name: '玉简碎片',
    type: 'za_wu',
    rarity: 'ling',
    description: '一枚碎裂的玉简残片，握在掌心微微发烫，似在指引着什么方向。',
    price: 20,
    stackable: false,
  },
  fei_zhai_ri_ji: {
    id: 'fei_zhai_ri_ji',
    name: '残破日记',
    type: 'za_wu',
    rarity: 'ling',
    description: '废宅旧主留下的发黄日记，墨迹潦草，反复写着一句话："若我当初再强一些……"。末页字迹颤抖，写着四个字——"血月将至"。',
    price: 5,
    stackable: false,
  },
};

/** 获取物品信息 */
export const getItem = (itemId: string): Item | undefined => itemsData[itemId];
